---
# Install some dev tools.

- hosts: all
  remote_user: vagrant
  become: yes
  gather_facts: yes
  tasks:
    - apt: name={{ item }} state=present
      with_items:
        - curl
        - tmux
  roles:
    - role: jmatt.editor-packages
